### ISSUE TITLE
Hellfire has invisible sprites. 

### ISSUE THREAD

**Issue by MetalMaxMX** [Clownacy/clownmdemu-core#13]
Hello! Great emulator, here I am playing on a Linux-based OS running Debian 11, and I built manually the 0.5.1 version. 

As I was testing several games, I came across Hellfire (USA) version that, for some reason, has invisible sprites for both the ship and the enemies! 

I am leaving a savestate, though it seems any version may encounter this bug during emulation? (ignore the .zip naming, that was just a way for me to upload the file containing the relevant info surrounding this game) 
[hellfirebug.zip](https://github.com/Clownacy/clownmdemu/files/13629162/hellfirebug.zip)

**Comment by BlastBrothers** [comment]
Fixed in v1.0.
