### ISSUE TITLE
Issues with EA games

### ISSUE THREAD

**Issue by BlastBrothers** [Clownacy/clownmdemu-core#19]
I didn't test _every_ EA game - there are lots - but here's what I happened to run into:

- [x] Crue Ball - boots to black screen with music
- [x] The Immortal, Jungle Strike, Marble Madness (US) - EA logo has corruption but otherwise fine. 
- [x] Road Rash, Road Rash II, Road Rash III, Skitchin' - EA logo has corruption, game crashes once a race starts. Pretty sure all of these games use the same engine so it should be the same fix for all of them.

**Comment by Clownacy** [comment]
I've heard that at least one EA game uses an undocumented plane size value, so that will need investigating too.

**Comment by Clownacy** [comment]
Crue Ball depends on H/V counter emulation. I dread implementing that thing.

**Comment by BlastBrothers** [comment]
Road Rash series and Skitchin' work in 1.0.
