### ISSUE TITLE
Rocket Knight Adventures - graphical glitch in intro

### ISSUE THREAD

**Issue by BlastBrothers** [Clownacy/clownmdemu-core#32]
The intro cutscene scrolls a graphic on Plane A up and down, as seen in[ this video](https://youtu.be/CQxW0RluwME?t=66).

However, this is what happens in the emulator:
![image](https://github.com/Clownacy/clownmdemu/assets/83738994/da374c01-08e3-40c0-bdef-dda778ca53a3)

Note that this intro is different in the Japanese version.

**Comment by Clownacy** [comment]
Fixed in v0.7.
