### ISSUE TITLE
After Burner II - title screen spheres flicker in and out of existence

### ISSUE THREAD

**Issue by BlastBrothers** [Clownacy/clownmdemu-core#33]
![image](https://github.com/Clownacy/clownmdemu/assets/83738994/5c6b9bbf-dd03-45b5-b5ad-d6a7d32c35af)

They're there most of the time, but they drop out every few frames. I checked on real hardware, and they stay visible the whole time.

**Comment by Clownacy** [comment]
Fixed in v0.8. May have had to do with 0d79d200f196a60bf4350feb380db193210e81ee.
