### ISSUE TITLE
Sonic 3D Blast: Corrupted Special Stages

### ISSUE THREAD

**Issue by Eggmanplant** [Clownacy/clownmdemu-core#54]
![Screenshot from 2024-06-06 14-08-54](https://github.com/Clownacy/clownmdemu/assets/126160675/88d3af7e-620b-4b21-896d-626879ab5958)

**Comment by ProximalElk6186** [comment]
Whoa, it seems that the emulator doesn't handle vertical interrupts very well...

**Comment by Clownacy** [comment]
Fixed (accidentally) in v1.0.
